services:
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: owntone
    network_mode: host 
    privileged: true
    restart: unless-stopped
    environment:
      - UID=0
      - GID=0
      - TZ=Asia/Ho_Chi_Minh
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./config:/etc/owntone
      - ./cache:/var/cache/owntone
      - /mnt/nasdata/media/music:/srv/media
      - /mnt/appsrv/ytb-owntone/pipes:/srv/music/pipes
      - ./config/asound.conf:/etc/asound.conf:ro
